module.exports = {
     CONNECTING: "CONNECTING",
     DISCONNECTING: "DISCONNECTING",

    // DISPATCH TYPES
     STORE_MESSAGES_TO_STATE: 'STORE_MESSAGES_TO_STATE',
     STORE_USERS_TO_STATE: 'STORE_USERS_TO_STATE',

    // REDUCER-SERVER SOCKET TYPES
     SEND_MESSAGE: 'SEND_MESSAGE',

    // CLIENT SOCKET TYPES
     UPDATE_MESSAGES: 'UPDATE_MESSAGES',
     ASSIGN_ROOM: 'ASSIGN_ROOM',

    // CLIENT-SERVER SOCKET TYPES
     JOIN_ROOM: 'JOIN_ROOM',
     GET_MESSAGES: 'GET_MESSAGES',
     GET_USERS: 'GET_USERS',

    // SERVER-CLIENT SOCKET TYPES
     SEND_CURRENT_USERS: 'SEND_CURRENT_USERS',
     SEND_CURRENT_MESSAGES: 'SEND_CURRENT_MESSAGES',
}