export const CONNECTING = "CONNECTING";
export const DISCONNECTING = "DISCONNECTING";

// DISPATCH TYPES
export const STORE_MESSAGES_TO_STATE = 'STORE_MESSAGES_TO_STATE';
export const STORE_USERS_TO_STATE = 'STORE_USERS_TO_STATE';

// REDUCER-SERVER SOCKET TYPES
export const SEND_MESSAGE = 'SEND_MESSAGE';

// CLIENT SOCKET TYPES
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const ASSIGN_ROOM = 'ASSIGN_ROOM';

// CLIENT-SERVER SOCKET TYPES
export const JOIN_ROOM = 'JOIN_ROOM';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_USERS = 'GET_USERS';

// SERVER-CLIENT SOCKET TYPES
export const SEND_CURRENT_USERS = 'SEND_CURRENT_USERS';
export const SEND_CURRENT_MESSAGES = 'SEND_CURRENT_MESSAGES';